### ISSUE TITLE
TN-232B - Implement an account balance field in the core DB to track Account Balance

### ISSUE THREAD

**Issue by tech-lead-humanID** [human-internet/humanid-core#30]

**Comment by ccrawford4** [comment]
This PR was completed by firman and merged into master branch: https://github.com/human-internet/humanid-core/commit/48a64d7c368760dade798f19b2ca633f0ca255fb

It involved updated the User Schema with an accountBalance field. It should be tested on staging.

**Comment by bastian-purrer** [comment]
@ccrawford4 who can approve this?

**Comment by bastian-purrer** [comment]
@Lunasocute please confirm status

**Comment by bastian-purrer** [comment]
@Lunasocute please check if implemented by checking if database table has accountBalance field

**Comment by tech-lead-humanID** [comment]
> @Lunasocute please check if implemented by checking if database table has accountBalance field

It has been updated.

**Comment by bastian-purrer** [comment]
Continued in https://github.com/human-internet/humanid-core/issues/46
